# Generated by Django 5.1.1 on 2024-11-27 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0003_alter_bookmodel_borrowed_by'),
        ('transaction', '0003_alter_transaction_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='Book.bookmodel'),
        ),
    ]
