# Generated by Django 5.1.1 on 2024-11-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0003_alter_bookmodel_borrowed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='is_borrowed',
            field=models.BooleanField(default=False),
        ),
    ]
