# Generated by Django 5.1.1 on 2024-11-27 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0005_bookmodel_reviews'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmodel',
            name='reviews',
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='reviews',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reviews.review'),
        ),
    ]
