# Generated by Django 5.1.1 on 2024-11-27 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0008_bookmodel_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmodel',
            name='reviews',
        ),
    ]
